### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by Om-Prakash-Verma** [Hushibul/9anime-clone#1]
Episode selection is not working and also instead of actual episode it is playing ads of 34 sec

**Comment by Hushibul** [comment]
Sorry to inform you that this is actullay just a demo video playing. There is no server in between. It's just a dummy frontend.

**Comment by Om-Prakash-Verma** [comment]
Can I get the orginal source code??

**Comment by Hushibul** [comment]
This is the original. I worked when I was learning react as a hobby project. 
I used the [aniwave.to](url) when as a referce for this site which has been shut down recently.
But you can use the [https://9animetv.to/home](url) as your reference since these two are quite identical.
If you need any kind of assistance feel free to ask.

**Comment by Om-Prakash-Verma** [comment]
Do u know the link structure to get videos from gogoanime??

**Comment by Hushibul** [comment]
You can get the link by inspecting. You can get the iframe and use their
html element and make your own design around it. I don't think you can get
the direct video link without purchasing a server or a streaming service.

**Comment by Om-Prakash-Verma** [comment]
Do u know anydirect streaming url?

**Comment by Hushibul** [comment]
Sorry I don't know about any direct streaming url. But you can check the VidStream, Mp4Upload, Dailymotion since any sites uses them if those can help you.

**Comment by Om-Prakash-Verma** [comment]
http://9anime.everythingavailable.online/home done

**Comment by Hushibul** [comment]
Very nicely done. Which api server are you using?
